[package]
name = "checkutf8"
version = "0.9.1"
authors = ["Manfred Lotz <manfred.lotz@posteo.de>"]
description = "A file checker to validate UTF-8."
edition = "2021"

[dependencies]

clap = { version = "4", features = ["derive"] }
